// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using boh_api.Data;

#nullable disable

namespace boh_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250527010611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Conjugation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConjugatedForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Person")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tense")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VerbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VerbId");

                    b.ToTable("Conjugations");
                });

            modelBuilder.Entity("Verb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsWeakVerb")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Verbs");
                });

            modelBuilder.Entity("Conjugation", b =>
                {
                    b.HasOne("Verb", "Verb")
                        .WithMany("Conjugations")
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verb");
                });

            modelBuilder.Entity("Verb", b =>
                {
                    b.Navigation("Conjugations");
                });
#pragma warning restore 612, 618
        }
    }
}
