// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using boh_api.Data;

#nullable disable

namespace boh_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250607151947_AddTagsTable")]
    partial class AddTagsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TagVerb", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.Property<int>("VerbsId")
                        .HasColumnType("integer");

                    b.HasKey("TagsId", "VerbsId");

                    b.HasIndex("VerbsId");

                    b.ToTable("VerbTags", (string)null);
                });

            modelBuilder.Entity("boh_api.Models.Conjugation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Form")
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupSort")
                        .HasColumnType("integer");

                    b.Property<int>("Sort")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VerbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VerbId");

                    b.ToTable("Conjugations");
                });

            modelBuilder.Entity("boh_api.Models.RelatedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("VerbId")
                        .HasColumnType("integer");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VerbId");

                    b.ToTable("RelatedWords");
                });

            modelBuilder.Entity("boh_api.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("boh_api.Models.Verb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Etymology")
                        .HasColumnType("text");

                    b.Property<string>("Infinitive")
                        .HasColumnType("text");

                    b.Property<int?>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Verbs");
                });

            modelBuilder.Entity("boh_api.Models.VerbDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VerbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VerbId");

                    b.ToTable("VerbDefinitions");
                });

            modelBuilder.Entity("boh_api.Models.VerbPronunciation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Pronunciation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VerbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VerbId");

                    b.ToTable("VerbPronunciations");
                });

            modelBuilder.Entity("TagVerb", b =>
                {
                    b.HasOne("boh_api.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("boh_api.Models.Verb", null)
                        .WithMany()
                        .HasForeignKey("VerbsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("boh_api.Models.Conjugation", b =>
                {
                    b.HasOne("boh_api.Models.Verb", "ParentVerb")
                        .WithMany("Conjugations")
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentVerb");
                });

            modelBuilder.Entity("boh_api.Models.RelatedWord", b =>
                {
                    b.HasOne("boh_api.Models.Verb", "ParentVerb")
                        .WithMany("RelatedWords")
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentVerb");
                });

            modelBuilder.Entity("boh_api.Models.VerbDefinition", b =>
                {
                    b.HasOne("boh_api.Models.Verb", "ParentVerb")
                        .WithMany("Definitions")
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentVerb");
                });

            modelBuilder.Entity("boh_api.Models.VerbPronunciation", b =>
                {
                    b.HasOne("boh_api.Models.Verb", "ParentVerb")
                        .WithMany("Pronunciations")
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentVerb");
                });

            modelBuilder.Entity("boh_api.Models.Verb", b =>
                {
                    b.Navigation("Conjugations");

                    b.Navigation("Definitions");

                    b.Navigation("Pronunciations");

                    b.Navigation("RelatedWords");
                });
#pragma warning restore 612, 618
        }
    }
}
